In [154]:
import numpy as np
from ml_from_scratch.helpers import cls_to_idx, idx_to_cls

In [155]:
class_match = ["iris-setosa", "iris-versicolor", "iris-virginica"]
indices = np.random.randint(0, 3, 10)
print(indices)
a = np.array(class_match)[indices]

[0 2 1 0 1 2 0 2 2 0]


In [156]:
np.vectorize(class_match.index)(a)

array([0, 2, 1, 0, 1, 2, 0, 2, 2, 0])

In [157]:
cls_to_idx(["a", "a", "b", "c", "a", "b"])

array([0, 0, 1, 2, 0, 1])

In [158]:
idx_to_cls(["a", "b", "c"], [0, 0, 1, 2, 0, 1])

array(['a', 'a', 'b', 'c', 'a', 'b'], dtype='<U1')

In [159]:
a = np.array([-1, 1, 2])
a

array([-1,  1,  2])

In [160]:
theta = np.array([[1, 2, 4],
                  [3, 4, -1],
                  [4, 1, 2]], dtype=np.float64)
theta

array([[ 1.,  2.,  4.],
       [ 3.,  4., -1.],
       [ 4.,  1.,  2.]])

In [161]:
a @ theta

array([10.,  4., -1.])

In [162]:
np.argmax(theta, axis=1)

array([2, 1, 0])

In [163]:
np.sum(np.array([[1, 2],
                 [3, 4]]), axis=0)

array([4, 6])

In [164]:
from ml_from_scratch.helpers import standardize

b = np.array([[1, 2, 7],
              [6, 7, 8],
              [11, 12, 13]])
b_std = standardize(b)
b_std

array([[-1.22474487, -1.22474487, -0.88900089],
       [ 0.        ,  0.        , -0.50800051],
       [ 1.22474487,  1.22474487,  1.3970014 ]])

In [165]:
res = b_std @ theta
res

array([[-8.45498304, -8.23747012, -5.45223639],
       [-2.03200203, -0.50800051, -1.01600102],
       [10.48698507,  8.74547063,  6.46823741]])

In [166]:
from ml_from_scratch.helpers import softmax, onehot

In [167]:
proba = softmax(res)

In [168]:
y_true = np.array([2, 1, 0])

### let's compute softmax grad

In [169]:
np.c_[proba, y_true]

array([[0.04467524, 0.0555305 , 0.89979426, 2.        ],
       [0.11972199, 0.54959069, 0.33068732, 1.        ],
       [0.83806122, 0.14687424, 0.01506454, 0.        ]])

In [170]:
n_features = b_std.shape[1]
n_classes = theta.shape[0]

In [171]:
class_k = 1

In [172]:
p_k = proba[:, class_k]
p_k

array([0.0555305 , 0.54959069, 0.14687424])

In [173]:
y_k = (y_true == class_k).astype(np.float64)
y_k

array([0., 1., 0.])

In [174]:
m = b_std.shape[0]

In [175]:
proba

array([[0.04467524, 0.0555305 , 0.89979426],
       [0.11972199, 0.54959069, 0.33068732],
       [0.83806122, 0.14687424, 0.01506454]])

In [176]:
y_onehot = onehot(y_true)

In [177]:
error = proba - y_onehot
error

array([[ 0.04467524,  0.0555305 , -0.10020574],
       [ 0.11972199, -0.45040931,  0.33068732],
       [-0.16193878,  0.14687424,  0.01506454]])

In [178]:
error.T

array([[ 0.04467524,  0.11972199, -0.16193878],
       [ 0.0555305 , -0.45040931,  0.14687424],
       [-0.10020574,  0.33068732,  0.01506454]])

In [179]:
error

array([[ 0.04467524,  0.0555305 , -0.10020574],
       [ 0.11972199, -0.45040931,  0.33068732],
       [-0.16193878,  0.14687424,  0.01506454]])

In [180]:
b_std

array([[-1.22474487, -1.22474487, -0.88900089],
       [ 0.        ,  0.        , -0.50800051],
       [ 1.22474487,  1.22474487,  1.3970014 ]])

In [181]:
nabla = (error.T @ b_std / m).T
nabla

array([[-0.08434982,  0.03729093,  0.04705889],
       [-0.08434982,  0.03729093,  0.04705889],
       [-0.10892129,  0.12820834, -0.01928705]])

In [182]:
error_k = p_k - y_k
error_k

array([ 0.0555305 , -0.45040931,  0.14687424])

In [183]:
nabla_k = error_k @ b_std / m
nabla_k

array([0.03729093, 0.03729093, 0.12820834])

In [184]:
theta

array([[ 1.,  2.,  4.],
       [ 3.,  4., -1.],
       [ 4.,  1.,  2.]])

In [185]:
theta = theta - 0.01*nabla
theta

array([[ 1.0008435 ,  1.99962709,  3.99952941],
       [ 3.0008435 ,  3.99962709, -1.00047059],
       [ 4.00108921,  0.99871792,  2.00019287]])